# oapi-codegen configuration for HawkSoft Partner API client generation
package: hawksoft
output: client/hawksoft.go
generate:
  client: true
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
